#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nfv-common
Version  : 1
Release  : 1
URL      : https://github.com/openstack/stx-nfv/archive/80a73c0af6752f535356cb4f937c0f11d765a798.tar.gz
Source0  : https://github.com/openstack/stx-nfv/archive/80a73c0af6752f535356cb4f937c0f11d765a798.tar.gz
Summary  : Nova Computer API Proxy
Group    : Development/Tools
License  : Apache-2.0
Requires: nfv-common-python
Requires: librt.so.1()(64bit)
Requires: nfv-common-legacypython
Requires: six
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
Nova Computer API Proxy

%package legacypython
Summary: legacypython components for the nfv-common package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the nfv-common package.


%package python
Summary: python components for the nfv-common package.
Group: Default

%description python
python components for the nfv-common package.


%prep
%setup -q -n stx-nfv-master

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537516963
pushd nfv/nfv-common
python2 setup.py build -b py2
popd

%install
rm -rf %{buildroot}
pushd nfv/nfv-common
python2 -tt setup.py build -b py2 install --root=%{buildroot}
popd
## install_append content
%global _sysconfdir '/usr/local/etc'
%clean
## install_append end

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
